config/routes.rb
RemoteSensing::Application.routes.draw do
  devise_for :users
  root :to => 'guest#index'
  resources :landsat_images do
    resources :previews, only: [:new, :create, :show] do
      member do
        get 'view_image' => "previews#view_image", :as => "view_image"
      end
    end
  end
  resources :users do
    collection do
      get 'edit_password' => "users#edit_password", :as => "edit_password"
      post 'change_password' => "users#change_password", :as => "change_password"
      get 'edit_email_address' => "users#edit_email_address", :as => "edit_email_address"
      post 'change_email_address' => "users#change_email_address", :as => "change_email_address"
      post 'change_level' => "users#change_level", :as => "change_level"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
				 :rememberable, :trackable, :validatable, :registerable

  attr_accessible :username, :password, :email, :password_confirmation, :remember_me
  has_many :landsat_images, :foreign_key => :creator_id, :dependent => :destroy

  def change_level(new_level_name)
    if new_level_name == "member"
      new_level = 0
    elsif new_level_name == "admin"
      new_level = 1
    end
    update_attribute(:level, new_level)
  end

  def admin?
    level_name == "admin"
  end

  def level_name
    if level == 0
      return "member"
    elsif level == 1
      return "admin"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @users = User.paginate(:page => params[:page], :per_page => 5).order("username asc")
     respond_to do |format|
      format.html
    end
  end

  def destroy
    @user = User.find(params[:id])
    identity = @user.username
    @user.destroy
    flash[:notice] = "User #{identity} successfully deleted"
    redirect_to users_path
  end

  def edit_password
    @user = current_user
    respond_to do |format|
      format.html
    end
  end

  def change_password
    @error = false
    @error = "Incorrect Password" if not current_user.valid_password? params[:user][:password]
    @error = "Password confirmation failed, please make sure the password confirmation same as the new password." if params[:user][:new_password] != params[:user][:password_confirmation]
    
    if not @error
      current_user.password = params[:user][:new_password]
      if current_user.save
        sign_in current_user, :bypass => true
        flash[:notice] = "Password successfully changed."
      else
        flash[:alert] = "Error. Password cannot be changed. #{current_user.errors.full_messages.join(",")}"
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_email_address
    respond_to do |format|
      format.html
    end
  end

  def change_email_address
    current_user.email = params[:email]
    if current_user.save
      sign_in current_user, :bypass => true
      flash[:notice] = "Email successfully changed."
    else
      flash[:alert] = "Error. Email cannot be changed. #{current_user.errors.full_messages.join(",")}"
    end
    respond_to do |format|
      format.js
    end
  end

  def change_level
    @user = User.find(params[:id])
    @success = @user.change_level(params[:new_level])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_email_address.js.erb
location.href = "<%= edit_email_address_users_path %>";

app/views/users/change_level.js.erb
<% if @success %>
  alert("<%=j "Level of #{@user.username} successfully changed to #{@user.level_name}"  %>");
<% else %>
  alert("<%=j "Something's wrong. Level of #{@user.username} cannot changed" %>");
<% end %>

app/views/users/change_password.js.erb
<% if @error %>
  alert("<%=j @error %>");
<% else %>
  location.href = "<%= edit_password_users_path %>";
<% end %>

app/views/users/edit_email_address.html.erb
<h1>Change Email Address</h1>
<hr>

<div class="row">
  <div class="col-md-4">
    <%= form_tag change_email_address_users_path, :method => :post, :remote=>true do %>
      <div class="form-group">
        <%= text_field_tag "email", current_user.email, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= submit_tag "Save", :class => "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit_password.html.erb
<h1>Change Password</h1>
<hr>

<div class="row">
  <div class="col-md-4">
    <%= form_tag change_password_users_path, :method => :post, :remote=>true do %>
      <div class="form-group">
        <%= password_field_tag "user[password]", "", :placeholder => "Old Password...", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= password_field_tag "user[new_password]", "", :placeholder => "New Password...", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= password_field_tag "user[password_confirmation]", "", :placeholder => "Password Confirmation...", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= submit_tag "Save", :class => "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Manage Users</h1>
<hr>

<% if @users.empty? %>
  <i style='font-size: 14px'>There is no user registered.</i>
<% else %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th width="1%">#</th>
        <th>Username</th>
        <th>Email Address</th>
        <th width="1%">Role</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= @users.offset + index + 1 %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td style="padding:0px;">
          <select class="form-control btn-user-level" style="width:120px; font-size:12px; padding: 0px" data-id="<%= user.id %>">
            <option value="admin" <%= "selected" if user.level_name == "admin" %>>Admin</option>
            <option value="member" <%= "selected" if user.level_name == "member" %>>Member</option>
          </select>
        </td>
        <td>
          <%= link_to raw('<i class="glyphicon glyphicon-trash"></i> Delete'), user_path(user.id), :method => :delete %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @users %>
<% end %>

<script type="text/javascript">
$(".btn-user-level").change(function(){
  var id = $(this).attr("data-id");
  var new_level = $(this).val();
  $.ajax({
    url:"<%=j change_level_users_path %>",
    dataType:"jsonp",
    type:"post",
    data:{
      id:id,
      new_level:new_level
    }
  })
});
</script>