config/routes.rb
RemoteSensing::Application.routes.draw do
  devise_for :users
  root :to => 'guest#index'
  resources :landsat_images do
    resources :previews, only: [:new, :create, :show] do
      member do
        get 'view_image' => "previews#view_image", :as => "view_image"
      end
    end
  end
  resources :users do
    collection do
      get 'edit_password' => "users#edit_password", :as => "edit_password"
      post 'change_password' => "users#change_password", :as => "change_password"
      get 'edit_email_address' => "users#edit_email_address", :as => "edit_email_address"
      post 'change_email_address' => "users#change_email_address", :as => "change_email_address"
      post 'change_level' => "users#change_level", :as => "change_level"
    end
  end
end

app/views/shared/_empty.html.erb
<tr>
  <td class='colspaned'>
    <center>
      <i>Data Kosong</i>
    </center>
  </td>
</tr>

app/views/shared/_flash.html.erb
<div id="flash">
  <% if notice %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  <% elsif alert %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/shared/_left_menu.html.erb
<ul class="nav navbar-nav">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Landsat Images <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to raw("<i class='glyphicon glyphicon-plus glyphicon-th-list'></i>&nbsp;Uploaded Landsat Images"), root_path %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to raw("<i class='glyphicon glyphicon-plus glyphicon-upload'></i>&nbsp;Upload New Landsat Image (GeoTIF)"), new_landsat_image_path %>
      </li>
    </ul>
  </li>
  <li>
    <% if can? :manage, :users %>
      <%= link_to raw("Manage Users"), users_path %>
    <% end %>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account Configuration <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to raw("<i class='glyphicon glyphicon-plus glyphicon-ok'></i>&nbsp;Change Password"), edit_password_users_path %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to raw("<i class='glyphicon glyphicon-plus glyphicon-envelope'></i>&nbsp;Change Email Address"), edit_email_address_users_path %>
      </li>
    </ul>
  </li>
</ul>

app/views/shared/_menu.html.erb
<div class="navbar-collapse collapse">
  <% if user_signed_in? %>
    <%= render :partial => "shared/left_menu" %>
  <% end %>

  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <p class="navbar-text pull-right">Welcome <%= current_user.username %>, <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Show/Hide Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Remote Sensing", root_path, :class => "navbar-brand" %>
    </div>

    <%= render :partial => "shared/menu" %>
  </div>
</div>