config/routes.rb
RemoteSensing::Application.routes.draw do
  devise_for :users
  root :to => 'guest#index'
  resources :landsat_images do
    resources :previews, only: [:new, :create, :show] do
      member do
        get 'view_image' => "previews#view_image", :as => "view_image"
      end
    end
  end
  resources :users do
    collection do
      get 'edit_password' => "users#edit_password", :as => "edit_password"
      post 'change_password' => "users#change_password", :as => "change_password"
      get 'edit_email_address' => "users#edit_email_address", :as => "edit_email_address"
      post 'change_email_address' => "users#change_email_address", :as => "change_email_address"
      post 'change_level' => "users#change_level", :as => "change_level"
    end
  end
end

app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
  def new
    @landsat_image = LandsatImage.find(params[:landsat_image_id])
    respond_to do |format|
      format.html
    end
  end

  def create
    @landsat_image = LandsatImage.find(params[:preview][:landsat_image_id])
    @preview = Preview.new(params[:preview])
    @preview_id = @preview.create_preview!
    respond_to do |format|
      format.js
    end
  end

  def show
    @landsat_image = LandsatImage.find(params[:landsat_image_id])
    @preview = Preview.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def view_image
    @preview = Preview.find(params[:id])
    send_file @preview.preview_file_path, :type => 'image/jpeg', :disposition => 'inline'
  end
end

app/views/previews/create.js.erb
<% if @preview_path == false %>
  alert("Something's Wrong. View for landsat image cannot be created.")
<% else %>
  alert("View for landsat image successfully created")
  location.href = "<%= landsat_image_preview_path(@landsat_image.id, @preview_id) %>";
<% end %>

app/views/previews/new.html.erb
<h1>View Setup for Landsat Image</h1>
<span><i><%= @landsat_image.name %>, uploaded at : <%= @landsat_image.created_at.strftime("%m/%d/%Y, %I:%M %p") %></i></span>
<hr>

<div class="modal fade" id="modal_preparation">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Preparing View for Landsat Image</h4>
      </div>
      <div class="modal-body">
        <center>
          <%= image_tag("loader.gif") %>
        </center>
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-default" data-dismiss="modal" id="btn_cancel">Cancel</button> -->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="row">
<form role="form" class="col-md-2">
  <div class="form-group">
    <label class="control-label">Quality (Pixel Density)</label>
    <br>
    <input name="preview[quality]" id="quality_slider" type="text" data-slider-min="1" data-slider-max="100" data-slider-step="1" data-slider-value="15"/>
  </div>
  <div class="form-group">
    <label class="control-label">Interpolation Method</label>
    <select name="preview[interpolation_method]" class="form-control" id="interpolation_method">
      <option value="0">Bilinear</option>
      <option value="1">Bicubic</option>
      <option value="2">Nearest Neighbor</option>
      <option value="3">Lancoz</option>
    </select>
  </div>
  <div class="form-group">
    <a href="#" class="btn btn-primary" id="btn_submit_preview">Submit</a>
  </div>
</form>
</div>

<script type="text/javascript">
$('#quality_slider').slider({
  formatter: function(value) {
    return value + "%";
  }
});

var xhrCreate = null;

xhrCreate = $("#btn_submit_preview").click(function(){
  var quality = $("#quality_slider").val()/100;
  var landsat_image_id = "<%= @landsat_image.id %>";
  $.ajax({
    url:"<%= landsat_image_previews_path(@landsat_image.id) %>",
    method:"post",
    dataType:"jsonp",
    data:{
      preview:{
        quality: quality,
        landsat_image_id: landsat_image_id,
        interpolation: $("#interpolation_method").val()
      }
    },
    beforeSend:function(){
      $("#modal_preparation").modal({
        backdrop: "static",
        show: true
      });
    },
    complete:function(){
      $("#modal_preparation").modal('hide');
    },
    failed:function(){
      alert("Error. View for landsat image cannot be created.");
    }
  });
  return false;
});

// $("#btn_cancel").click(function(){
//   xhrCreate.abort();
// });
</script>

app/views/previews/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Description</h3>
      </div>
      <div class="panel-body">
        <table border="0" style="font-size:10px">
          <tr>
            <td>Name</td>
            <td width="1%">:&nbsp;</td>
            <td><%= @landsat_image.ori_name %></td>
          </tr>
          <tr>
            <td>Uploaded at</td>
            <td width="1%">:&nbsp;</td>
            <td><%= @landsat_image.created_at.strftime("%m/%d/%Y, %I:%M %p") %></td>
          </tr>
          <tr>
            <td>Pixel Density</td>
            <td width="1%">:&nbsp;</td>
            <td><%= @preview.quality * 100  %>%</td>
          </tr>
          <tr>
            <td>Interpolation</td>
            <td width="1%">:&nbsp;</td>
            <td><%= @preview.interpolation_name  %></td>
          </tr>  
          <% geo_transform = @preview.geo_transform %>
          <tr>
            <td>West</td>
            <td width="1%">:&nbsp;</td>
            <td><%= geo_transform[:west]  %></td>
          </tr>
          <tr>
            <td>North</td>
            <td width="1%">:&nbsp;</td>
            <td><%= geo_transform[:north]  %></td>
          </tr>
          <tr>
            <td>Projection</td>
            <td width="1%">:&nbsp;</td>
            <td><%= @preview.projection  %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div id="landsat_image_preview_box">
      <img src="<%= view_image_landsat_image_preview_path(@landsat_image.id, @preview.id) %>">
      <div style="position:absolute; left:30px; top: 10px; text-align:center; opacity: 0.3; transition:1s" onmouseover="this.style.opacity=1" onmouseout="this.style.opacity=0.3">
        <h4 style="color:#149bdf">Zoom</h4>
        <input id="zoom_slider" type="text" data-slider-min="10" data-slider-max="400" data-slider-step="1" data-slider-value="100" data-slider-orientation="vertical"/>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
(function(){
  var $box = $("#landsat_image_preview_box");
  $box.css("max-width", $box.parent().width());

  var $img = $box.find("img");
  var w = null;
  var h = null;
  $("#zoom_slider").slider({
    formatter: function(value) {
      return value + "%";
    },
    reversed:true
  }).on("slide", function(){
    if (w == null) w = $img.width();
    if (h == null) h = $img.height();
    var factor = $("#zoom_slider").data('slider').getValue() / 100;
    $img.width(w * factor);
    $img.height(h * factor);
  })
})()
</script>