config/routes.rb
RemoteSensing::Application.routes.draw do
  devise_for :users
  root :to => 'guest#index'
  resources :landsat_images do
    resources :previews, only: [:new, :create, :show] do
      member do
        get 'view_image' => "previews#view_image", :as => "view_image"
      end
    end
  end
  resources :users do
    collection do
      get 'edit_password' => "users#edit_password", :as => "edit_password"
      post 'change_password' => "users#change_password", :as => "change_password"
      get 'edit_email_address' => "users#edit_email_address", :as => "edit_email_address"
      post 'change_email_address' => "users#change_email_address", :as => "change_email_address"
      post 'change_level' => "users#change_level", :as => "change_level"
    end
  end
end

app/models/landsat_image.rb
class LandsatImage < ActiveRecord::Base
  attr_accessible :name, :ori_name
  before_destroy :remove_files
  belongs_to :creator, class_name: 'User'

  def data_path
    base = File.join("..", "landsat_images_data")
    landsat_image_path = File.join(base, id.to_s)
  end

  def remove_files
    puts ">>>>>>>>>>>>>>>>>>> DELETE : #{data_path}"
    FileUtils.rm_rf data_path
  end
end

app/controllers/landsat_images_controller.rb
class LandsatImagesController < ApplicationController
  def new
    @landsat_image = LandsatImage.new
    respond_to do |format|
      format.html
    end
  end

  def create
    @landsat_image = LandsatImage.new(params[:landsat_image])
    @landsat_image.creator_id = current_user.id
    filename = params[:landsat_image_file].original_filename
    @landsat_image.ori_name = filename
    if @landsat_image.save
      directory = "landsat_images_data"
      directory = File.join("..", directory, @landsat_image.id.to_s)
      Dir.mkdir(directory) unless Dir.exist?(directory)

      path = File.join(directory, filename)
      File.open(path, "wb") { |f| f.write(params[:landsat_image_file].read) }
      flash[:notice] = "Landsat image #{filename} successfully uploaded"
    else
      flash[:alert] = "Something's wrong, landsat image #{filename} cann't be uploaded"
    end
    render :inline => ""
  end

  def destroy
    @landsat_image = LandsatImage.find(params[:id])
    identity = @landsat_image.ori_name
    @landsat_image.destroy
    flash[:notice] = "Landsat image #{identity} successfully deleted"
    redirect_to root_path
  end

  def setup_view
    @landsat_image = LandsatImage.find(params[:id])
    respond_to do |format|
      format.html
    end
  end
end

app/views/landsat_images/_form.html.erb
<%= form_for(landsat_image, html:{ role:"form", id:"landsat_image_upload_form", enctype:"multipart/form-data"}) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control", id:"landsat_image_name_input" %>
    <span class="help-block"></span>
  </div>
  <div class="form-group">
    <label class="control-label"></label>
    <input type="file" name="landsat_image_file" id="landsat_image_file_input">
    <span class="help-block"></span>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-primary", :id => "btn_upload_landsat_image" , :value => "Upload" %>
  </div>
<% end %>

<script type="text/javascript">
$("#landsat_image_upload_form").ajaxForm({
  beforeSend: function() {
    $("#modal_preparation").modal({
      show:true,
      backdrop:"static"
    });
  },
  uploadProgress: function(event, position, total, percentComplete) {
    $("#progress").attr("aria-valuenow", percentComplete).css("width", percentComplete + "%");
    if (percentComplete == 100) {
      $("#progress_container").hide();
      $("#loading").show();
    }
  },
  complete: function(xhr) {
    alert("Landsat image successfully uploaded.");
    location.href="<%= root_path %>"
  }
});

$("#landsat_image_file_input").change(function(){
  var $nameInput = $("#landsat_image_name_input");
  var path = $("#landsat_image_file_input").val();
  var filename = path.substring(path.lastIndexOf("\\")+1, path.length);
  $nameInput.val(filename);
});
</script>

app/views/landsat_images/_table.html.erb
<% if @landsat_images.empty? %>
  <i style='font-size: 14px'>There is no landsat images uploaded.</i>
<% else %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th width="1%">#</th>
        <th>Name</th>
        <th>Uploaded at</th>
        <th>Uploaded by</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @landsat_images.each_with_index do |landsat_image, index| %>
      <tr>
        <td><%= @landsat_images.offset + index + 1 %></td>
        <td><%= landsat_image.name %></td>
        <td><%= landsat_image.created_at.strftime("%m/%d/%Y, %I:%M %p") %></td>
        <td>
          <% if landsat_image.creator.id == current_user.id %>
            <i><%= landsat_image.creator.username %></i>
          <% else %>
            <%= landsat_image.creator.username %>
          <% end %>
        </td>
        <td>
          <%= link_to raw('<i class="glyphicon glyphicon-fullscreen"></i> View'), new_landsat_image_preview_path(landsat_image.id) %>
          <% if landsat_image.creator.id == current_user.id %>
            |
            <%= link_to raw('<i class="glyphicon glyphicon-trash"></i> Delete'), landsat_image_path(landsat_image.id), :method => :delete %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @landsat_images %>
<% end %>

app/views/landsat_images/new.html.erb
<h1>Upload New Landsat Image (GeoTIFF)</h1>
<hr>
<div class="modal fade" id="modal_preparation">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Uploading Landsat Image</h4>
      </div>
      <div class="modal-body">
        <center>
          <div class="progress progress-striped" id="progress_container">
            <div class="progress-bar progress-bar-info" id="progress" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
              <span class="sr-only">20% Complete</span>
            </div>
          </div>
          <div id="loading" style="display:none">
            <%= image_tag('loader.gif') %>
          </div>
        </center>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
<%= render :partial => "form", locals: { landsat_image: @landsat_image } %>